// Vercel Function entry. The real handler is the esbuild bundle produced at
// build time (see esbuild.mjs); the explicit .cjs path makes Vercel's tracer
// ship it. A vercel.json rewrite sends every `/api/*` request to this single
// function with the original URL preserved, and the Hono app already mounts its
// routes under `/api`, so paths match unchanged.
// @ts-expect-error - ../dist/index.cjs is generated by esbuild during the build
import bundle from '../dist/index.cjs'

export const config = {
  maxDuration: 60,
  // Let the Hono adapter read the raw request stream instead of Vercel parsing it.
  api: {
    bodyParser: false,
  },
}

// The CJS bundle exposes the handler as its `default` export under Node's
// ESM↔CJS interop; fall back to the module itself just in case.
export default bundle.default ?? bundle
