// AUTO-GENERATED from apps/api/app/core/especialidades.json by `npm run sync:especialidades`.
// Do not edit by hand — edit the JSON (the single source of truth) and re-run.
export const ESPECIALIDADES = [
  "Acólito",
  "Aeroespacial",
  "Agricultor",
  "Agricultor Urbano",
  "Alfaiate/Modista",
  "Ambientalista",
  "Animador Comunitário",
  "Animador da Fé",
  "Animador Litúrgico",
  "Arqueologia",
  "Arquitetura e Urbanismo",
  "Artes Marciais",
  "Astrónomo",
  "Atleta",
  "Ator",
  "Bibliotecário",
  "Biblista",
  "Biólogo",
  "Bom Consumidor",
  "Botânico",
  "Bushcraft",
  "Campista",
  "Canoista",
  "Cantor",
  "Cantor Litúrgico",
  "Carpinteiro",
  "Carpinteiro Naval",
  "Cavaleiro",
  "Ciclista",
  "Cidadania e Voluntariado",
  "Cidadão Cristão",
  "Cidadão do Mundo",
  "Cidadão Europeu",
  "Cidadão Lusófono",
  "Colecionador",
  "Comunicador",
  "Condutor",
  "Corredor de Orientação",
  "Cozinha em Campo",
  "Cozinheiro",
  "Cozinheiro do Mundo",
  "Cuidador",
  "Culturas do Mundo",
  "Dança",
  "Defesa Nacional",
  "Desenhador",
  "Desportista",
  "Desportos de Deslize sobre Água",
  "Desportos de Deslize sobre Rodas",
  "Desportos de Inverno",
  "Desportos de Precisão",
  "Desportos de Raquete",
  "Desportos Inclusivos",
  "Desportos Radicais",
  "Diálogo Inter-Religioso",
  "Doméstico",
  "Ecumenismo",
  "Editor de Vídeo",
  "Eletricista",
  "Eletrónica",
  "Empreendorismo e Inovação",
  "Energia",
  "Engenharia",
  "Entomólogo",
  "Escalador",
  "Escrita Criativa",
  "Escutismo Seguro",
  "Esgrima",
  "Espeleologia",
  "Ferramentas de Corte",
  "Física",
  "Fogo de Conselho",
  "Fotógrafo",
  "Fotógrafo Naturalista",
  "Geocaching",
  "Geógrafo",
  "Geólogo",
  "Gestão de Projetos e Investimentos",
  "Ginasta",
  "Guarda-Rios",
  "Guia de Região",
  "Guia do Património Religioso",
  "Herpetólogo",
  "História do CNE",
  "Historiador",
  "Informático",
  "Intendente",
  "Internet Segura",
  "Intérprete",
  "Jogos de Mesa",
  "Jornalista",
  "Leis e Justiça",
  "Leitor",
  "Líder de Expedição",
  "Linguagem não Verbal",
  "Malacolista",
  "Marinharia",
  "Matemático",
  "Mergulhador",
  "Mestre do Leme",
  "Metalúrgico/Mecânico",
  "Meteorologista",
  "Micólogo",
  "Missionário Católico",
  "Modelismo",
  "Montanhista",
  "Músico",
  "Músico Litúrgico",
  "Nadador",
  "Nadador Salvador",
  "Nutrição",
  "Oceanógrafo",
  "Ornitólogo",
  "Paleontologia",
  "Pasteleiro",
  "Pedestrianista",
  "Pedreiro",
  "Peregrino",
  "Pescador",
  "Pintor",
  "Pioneirista",
  "Podcaster",
  "Política e Cidadania Ativa",
  "Prevenção em Saúde",
  "Proteção Civil",
  "Protetor da Natureza",
  "Protetor da Vida Marinha",
  "Protetor dos Animais",
  "Publicidade e Marketing",
  "Química",
  "Radioamador",
  "Radioescuteiro",
  "Realizador",
  "Reciclador",
  "Relações Públicas",
  "Robótica",
  "Saltimbanco",
  "Sapador",
  "Sinaleiro",
  "Sobrevivência",
  "Socorrista",
  "Técnica Aeronáutica",
  "Teólogo",
  "Topógrafo",
  "Trabalhos Manuais/Bricolagem",
  "Tradutor",
  "Turismo",
  "Velejador",
  "Vendas",
  "Veterinária",
  "Vigilante da Natureza",
  "Voluntário Internacional",
  "Zoólogo",
] as const satisfies readonly string[]
